### ISSUE TITLE
TypeError: expected string or buffer in "re.py", line 141, in match

### ISSUE THREAD

**Issue by Marty-Macfly** [projectgus/yamdwe#30]
Hello,

I tried to launch yamdwe, on a mediawiki 1.1.16 and i've got the following stack trace:

```
Traceback (most recent call last):
  File "./yamdwe/yamdwe.py", line 93, in <module>
    main()
  File "./yamdwe/yamdwe.py", line 61, in main
    exporter.write_pages(pages)
  File "yamdwe/dokuwiki.py", line 41, in write_pages
    self._convert_page(page)
  File "yamdwe/dokuwiki.py", line 97, in _convert_page
    content = wikicontent.convert_pagecontent(full_title, revision["*"])
  File "yamdwe/wikicontent.py", line 68, in convert_pagecontent
    return convert(root, context, False)
  File "yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "yamdwe/wikicontent.py", line 85, in convert
    return convert_children(node, context)
  File "yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "yamdwe/wikicontent.py", line 114, in convert
    print("Unknown tagname %s" % section.tagname)
  File "yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "yamdwe/wikicontent.py", line 260, in convert
    if node.__class__ != Node:
  File "yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "yamdwe/wikicontent.py", line 89, in convert
    return convert_children(node, context) + "\n"
  File "yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "yamdwe/wikicontent.py", line 94, in convert
    if text._text is NoneType:
  File "env/lib64/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

I had some debug to the code to find out the origin of that error and it's producing when `text._text` is `None`.

**Comment by projectgus** [comment]
Hi Marty,

Thanks for reporting this.

I think this should be easy to fix, but just to be sure I fix it properly - any possibility you have an example of Mediawiki content that causes this error?

Thanks,


Angus

**Comment by Marty-Macfly** [comment]
Hello,

I don't know which page is doing this error. How can i provide you the data ? I can also test your fix, if you want ?

Regards,
Mac

**Comment by lordofbikes** [comment]
I run into the same issue recently, here is what I figured out:

The page, where the error occurs is here: http://wiki.librecad.org/index.php?title=Commands&oldid=1605

The source of the last working revision 16 is here: http://download.librecad.de/commands_16.txt
The source of the bad revision 17 is here: http://download.librecad.de/commands_17.txt

Armin

**Comment by projectgus** [comment]
Hi,

Sorry for the very long delay in updating this issue. I finally had some time to work on wikis again tonight.

It looks like it was caused by having `__NOTOC__` in the mediawiki page. The unhandled exception should be fixed, and as bonus `__NOTOC__` is now correctly converted to `~~NOTOC~~` in the dokuwiki output.

**Comment by projectgus** [comment]
PS Thanks @lordofbikes for the excellent test case and sample good/bad content. Made verifying the cause and fix very simple!

**Comment by Marty-Macfly** [comment]
Great, i 'll test that soon :)

**Comment by projectgus** [comment]
Awesome, please let me know how it goes!

**Comment by lordofbikes** [comment]
The fix works for me, thus I'm fine with closing this issue.

The test case was the result of my debugging efforts. As I couldn't find a working solution, I'm glad that it helped you fixing this.

**Comment by Marty-Macfly** [comment]
Works for me thanks :)

**Comment by Marty-Macfly** [comment]
Sorry, i replied too quickly it goes one step further but same error again. How can i give you some useful information ?
...
Converting 40 revisions of page 'Accueil'...
Traceback (most recent call last):
  File "./yamdwe/yamdwe.py", line 93, in <module>
    main()
  File "./yamdwe/yamdwe.py", line 61, in main
    exporter.write_pages(pages)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/dokuwiki.py", line 41, in write_pages
    self._convert_page(page)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/dokuwiki.py", line 97, in _convert_page
    content = wikicontent.convert_pagecontent(full_title, revision["*"])
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 68, in convert_pagecontent
    return convert(root, context, False)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 85, in convert
    return convert_children(node, context)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 113, in convert
    return result + convert_children(section, context)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 259, in convert
    return convert_children(node, context)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 89, in convert
    return convert_children(node, context) + "\n"
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 75, in convert_children
    res = convert(child, context, result.endswith("\n"))
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 142, in __call__
    return self.call_internal(lambda f:f, args, kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/visitor.py", line 165, in call_internal
    result = func_modifier(self.registry[t])(*args, **kw)
  File "/home/macfly/Lbn/migration-wiki/yamdwe/wikicontent.py", line 93, in convert
    m = re.match(r"<__yamdwe_nowiki>([0-9]+)</__yamdwe_nowiki>", text._text)
  File "/home/macfly/Lbn/migration-wiki/env/lib64/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
...

**Comment by projectgus** [comment]
Sorry to hear it's still not working. :(

But... are you sure you have the latest version of yamdwe? The line numbers in the stack trace you supplied don't match the current version of yamdwe, but they do match the version before the fix for this bug was applied.

**Comment by Marty-Macfly** [comment]
Sorry, i'm going to throw myself through the window... It works fine when you do an update of the code, thanks for the fix.
